# Generated by Django 2.1.2 on 2018-10-05 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('pub_status', models.CharField(choices=[('d', 'Draft'), ('a', 'Approved'), ('p', 'Published')], default='d', max_length=1)),
                ('catagory', models.CharField(choices=[('p', 'Politics'), ('s', 'Sport'), ('a', 'Art, Music & Entertainment')], max_length=1)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='auther',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auther_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspanel.auther'),
        ),
    ]
