# Generated by Django 2.1.2 on 2018-10-05 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='articles',
            new_name='article',
        ),
    ]
