# Generated by Django 2.1.2 on 2018-10-06 07:02

from django.db import migrations


class Migration(migrations.Migration):
	atomic = False
	dependencies = [('newspanel', '0004_auto_20181006_0957'),]

	operations = [ migrations.RenameModel(old_name='auther',new_name='Author',),migrations.RenameField(model_name='author',old_name='auther_name',new_name='author_name',),]
