# Generated by Django 2.1.2 on 2018-10-06 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newspanel', '0006_auto_20181006_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pub_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_status_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspanel.Pub_status'),
        ),
    ]
