# Generated by Django 2.1.2 on 2018-10-07 09:06

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ('newspanel', '0007_auto_20181006_1533'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='catagory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='catagory_name',
            new_name='category_name',
        ),
    ]
